builds:
  - binary: ensync-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/ensync-cli/pkg/version.version={{ .Version | default "dev" }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{- title .Os }}_{{- if eq .Arch \"amd64\" }}x86_64{{- else }}{{ .Arch }}{{ end }}"
    files:
      - README.md
      - LICENSE
      - examples/
      - Writerside/
  - format: zip
    name_template: "{{ .ProjectName }}_{{- title .Os }}_{{- if eq .Arch \"amd64\" }}x86_64{{- else }}{{ .Arch }}{{ end }}"

checksum:
  name_template: "checksums.txt"
